# Generated by Django 4.0.4 on 2022-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_external_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="external_user_id",
        ),
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
