# Generated by Django 4.0.4 on 2022-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_external_user_id_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
