# Generated by Django 4.0.4 on 2022-05-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
