# Generated by Django 4.0.4 on 2022-05-13 13:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
    ]
