# Generated by Django 4.0.4 on 2022-05-06 14:47

from django.db import migrations, models

import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="uuid",
            field=models.CharField(default=tasks.models.generate_uuid, max_length=128),
        ),
    ]
