# Generated by Django 4.0.4 on 2022-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="uuid",
            new_name="public_id",
        ),
    ]
